In [101]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [102]:
dataset = pd.read_csv('healthcare-dataset-stroke-data.csv')
dataset.head(10)

id  gender   age  hypertension  heart_disease ever_married  \
0   9046    Male  67.0             0              1          Yes   
1  51676  Female  61.0             0              0          Yes   
2  31112    Male  80.0             0              1          Yes   
3  60182  Female  49.0             0              0          Yes   
4   1665  Female  79.0             1              0          Yes   
5  56669    Male  81.0             0              0          Yes   
6  53882    Male  74.0             1              1          Yes   
7  10434  Female  69.0             0              0           No   
8  27419  Female  59.0             0              0          Yes   
9  60491  Female  78.0             0              0          Yes   

       work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0        Private          Urban             228.69  36.6  formerly smoked   
1  Self-employed          Rural             202.21   NaN     never smoked   
2        Private          Rural             105.92  32.5     never smoked   
3        Private          Urban             171.23  34.4           smokes   
4  Self-employed          Rural             174.12  24.0     never smoked   
5        Private          Urban             186.21  29.0  formerly smoked   
6        Private          Rural              70.09  27.4     never smoked   
7        Private          Urban              94.39  22.8     never smoked   
8        Private          Rural              76.15   NaN          Unknown   
9        Private          Urban              58.57  24.2          Unknown   

   stroke  
0       1  
1       1  
2       1  
3       1  
4       1  
5       1  
6       1  
7       1  
8       1  
9       1

In [103]:
dataset['bmi'] = dataset['bmi'].fillna(0)

ave = dataset['bmi'].mean()
dataset['bmi'] = dataset['bmi'].replace(0, ave) #Replacing zeros with average BMI

In [104]:
dataset.drop(columns=['id'],inplace=True)

In [105]:
#Converting Gender to categorical
dataset.head(10)
dataset['gender'] = dataset['gender'].astype('category')
dataset['gender'] = dataset['gender'].cat.codes
dataset.head(10)

gender   age  hypertension  heart_disease ever_married      work_type  \
0       1  67.0             0              1          Yes        Private   
1       0  61.0             0              0          Yes  Self-employed   
2       1  80.0             0              1          Yes        Private   
3       0  49.0             0              0          Yes        Private   
4       0  79.0             1              0          Yes  Self-employed   
5       1  81.0             0              0          Yes        Private   
6       1  74.0             1              1          Yes        Private   
7       0  69.0             0              0           No        Private   
8       0  59.0             0              0          Yes        Private   
9       0  78.0             0              0          Yes        Private   

  Residence_type  avg_glucose_level        bmi   smoking_status  stroke  
0          Urban             228.69  36.600000  formerly smoked       1  
1          Rural             202.21  27.756732     never smoked       1  
2          Rural             105.92  32.500000     never smoked       1  
3          Urban             171.23  34.400000           smokes       1  
4          Rural             174.12  24.000000     never smoked       1  
5          Urban             186.21  29.000000  formerly smoked       1  
6          Rural              70.09  27.400000     never smoked       1  
7          Urban              94.39  22.800000     never smoked       1  
8          Rural              76.15  27.756732          Unknown       1  
9          Urban              58.57  24.200000          Unknown       1

In [106]:
#Converting marital status to categorical
dataset['ever_married'] = dataset['ever_married'].astype('category')
dataset['ever_married'] = dataset['ever_married'].cat.codes

In [107]:
#Converting work type, residence type and smoking status to categorical
dataset['work_type'] = dataset['work_type'].astype('category')
dataset['work_type'] = dataset['work_type'].cat.codes
dataset['Residence_type'] = dataset['Residence_type'].astype('category')
dataset['Residence_type'] = dataset['Residence_type'].cat.codes
dataset['smoking_status'] = dataset['smoking_status'].astype('category')
dataset['smoking_status'] = dataset['smoking_status'].cat.codes

In [108]:
dataset.head(10)

gender   age  hypertension  heart_disease  ever_married  work_type  \
0       1  67.0             0              1             1          2   
1       0  61.0             0              0             1          3   
2       1  80.0             0              1             1          2   
3       0  49.0             0              0             1          2   
4       0  79.0             1              0             1          3   
5       1  81.0             0              0             1          2   
6       1  74.0             1              1             1          2   
7       0  69.0             0              0             0          2   
8       0  59.0             0              0             1          2   
9       0  78.0             0              0             1          2   

   Residence_type  avg_glucose_level        bmi  smoking_status  stroke  
0               1             228.69  36.600000               1       1  
1               0             202.21  27.756732               2       1  
2               0             105.92  32.500000               2       1  
3               1             171.23  34.400000               3       1  
4               0             174.12  24.000000               2       1  
5               1             186.21  29.000000               1       1  
6               0              70.09  27.400000               2       1  
7               1              94.39  22.800000               2       1  
8               0              76.15  27.756732               0       1  
9               1              58.57  24.200000               0       1

In [109]:
#Seperating Features and dependant variable
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [110]:
from sklearn.model_selection import train_test_split

In [111]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)

In [112]:
#Feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test) 

In [113]:
#Simple Logistic Regression Model
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train,y_train)

classifier.predict(sc.transform([[1,75.0,0,1,0,2,1,5000,36,1]]))
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))


from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)

accuracy_score(y_test,y_pred)

[[0 1]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]
[[1213    0]
 [  65    0]]


0.9491392801251957

In [115]:
#Naive Bayes Model
from sklearn.naive_bayes import GaussianNB
classifier1 = GaussianNB()
classifier1.fit(X_train,y_train)

classifier1.predict(sc.transform([[1,75.0,0,1,0,2,1,5000,36,1]]))

y_pred = classifier1.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

cm = confusion_matrix(y_test,y_pred)
print(cm)

accuracy_score(y_test,y_pred)

[[1 1]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]
[[1096  117]
 [  35   30]]


0.8810641627543035

In [116]:
import pickle
pickle.dump(classifier, open('model.pkl','wb'))
pickle.dump(classifier1, open('model1.pkl','wb'))
